language: objective-c

before_script:
 ant test
 
script: xcodebuild -project ../generated-apps/iOS/ConApp.xcodeproj -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO 

after_success:
    "zip -r generated-apps.zip ../generated-apps && curl -T generated-apps.zip -u $FTP_USER:$FTP_PASS ftp.hosting-agency.de/public_html/dukecon-apps/"
