language: objective-c

before_install: 
  - sudo apt-get install -qq openjdk-7-jre-headless
  - sudo apt-get install -qq ant

before_script: ant test
 
script: xcodebuild -project ../generated-apps/iOS/ConApp.xcodeproj -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO 

after_success:
    "zip -r GeneratedConApp.zip /Users/travis/build/rytina/dukecon_appsgenerator/build/Release-iphonesimulator/ConApp.app && curl -T GeneratedConApp.zip -u $FTP_USER:$FTP_PASS ftp.hosting-agency.de/public_html/dukecon-apps/"
