language: objective-c

before_install: 
  - brew tap caskroom/cask
  - brew install brew-cask
  - brew update
  - brew cask install java
  - brew install ant


before_script: ant test && chmod -R 777 ../generated-apps
 
script: xcodebuild -project ../generated-apps/iOS/ConApp.xcodeproj -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO 

after_success:
   "zip -r generated-apps.zip ../generated-apps && curl -T generated-apps.zip -u $FTP_USER:$FTP_PASS ftp.hosting-agency.de/public_html/dukecon-apps/"
   #"zip -r GeneratedConApp.zip /Users/travis/build/rytina/dukecon_appsgenerator/build/Release-iphonesimulator/ConApp.app && curl -T GeneratedConApp.zip -u $FTP_USER:$FTP_PASS ftp.hosting-agency.de/public_html/dukecon-apps/"
